data:
  train_urls:
      - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
  validation_urls:
      - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
  cache_dir: "gs://pubmed-mosaic/tokenized/openwebtext/"
model:
  hidden_dim: 1280
  num_heads: 20
  num_layers: 36
  seq_len: 512
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
  num_senses: 48
  sense_intermediate_scale: 7
trainer:
  wandb:
    project: "levanter"
    tags: [ "openwebtext", "backpack"]

  mp: p=f32,c=bfloat16
  learning_rate: 2E-4
  weight_decay: 0.1
  model_axis_size: 1
  num_train_steps: 100000
  train_batch_size: 1024
  per_device_parallelism: 16

  axis_resources:
    batch: "data"
    vocab: "model"
    mlp: "model"
    heads: "model"
  parameter_axis_resources:
    embed: "data"
