data:
  datasets:
    - train_urls:
        - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_train.{1..128}-of-128.jsonl.gz"
      validation_urls:
        - "gs://pubmed-mosaic/openwebtext-sharded/openwebtext_val.{1..8}-of-8.jsonl.gz"
      cache_dir: "gs://levanter-data/tokenized/openwebtext/"
      tokenizer: "gpt2"
      weight: 0.5
    - train_urls:
        - gs://levanter-data/pile/train/{00..29}.jsonl.zst
      validation_urls:
        - gs://levanter-data/pile/val.jsonl.zst
      cache_dir: "gs://levanter-data/tokenized/pile-old/"
      tokenizer: "EleutherAI/gpt-neox-20b"
      weight: 0.5
model:
  type: gpt2
  hidden_dim: 768
  num_heads: 12
  num_layers: 12
  seq_len: 1024
  gradient_checkpointing: true
  scale_attn_by_inverse_layer_idx: true
trainer:
  wandb:
    project: "levanter"
    tags: [ "openwebtext", "gpt2"]

  mp: p=f32,c=bfloat16
  model_axis_size: 1
  per_device_parallelism: 4

  train_batch_size: 512
optimizer:
  learning_rate: 6E-4
  weight_decay: 0.1
  min_lr_ratio: 0.1
